// Generated by CoffeeScript 1.8.0
(function() {
  var blackButton, blueButton, changeStyle, setCookie, style;

  style = $("#styles");

  blackButton = $("#blackButton");

  blueButton = $("#whiteButton");

  blackButton.click(function() {
    return changeStyle("style1.css");
  });

  blueButton.click(function() {
    return changeStyle("style2.css");
  });

  changeStyle = function(stylesheet) {
    style.attr({
      href: stylesheet
    });
    return setCookie(stylesheet);
  };

  setCookie = function(stylesheet) {
    return $.cookie('style', stylesheet, {
      expires: 7
    });
  };

  $(function() {
    var sheet;
    sheet = $.cookie('style');
    if (sheet) {
      changeStyle(sheet);
      return console.log(sheet);
    } else {
      return changeStyle('style1.css');
    }
  });

}).call(this);
